name: Test Workflow
on:
  workflow_dispatch:
  push:
    branches: [ 'main' ]

jobs:
  #  my_first_job:
  #    runs-on: ubuntu-latest
  #    steps:
  #      - name: Checkout
  #        uses: actions/checkout@v6.0.0
  #
  #      - name: Setup Node
  #        uses: actions/setup-node@v6.0.0
  #        with:
  #          node-version: 16.13.x
  #          cache: npm
  #
  #      - name: Install
  #        run: npm ci
  #
  #      - name: Hello World
  #        run: echo "Hello Github Actions!"
  #
  #      - name: List files
  #        run: ls -la

  my_second_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.0

      - name: Setup Node
        uses: actions/setup-node@v6.0.0
        with:
          node-version: 16.13.x
          cache: npm

      - name: Install
        run: npm ci

      - name: Lint
        run: npm run eslint:check

      - name: Unit Tests
        run: npm run mocha:test

      - name: Generate coverage report
        run: npm run nyc:run
#        Run & Export coverage report [HTML FILE]
#        run: npm run nyc:run && npm run nyc:coverage

      - name: Functional Tests
        run: npm run cypress:test

      - name: Generate JSdoc
        run: "jsdoc modules/ -d docs"
